[theme]
# Primary color for your app. This color is widely used across components.
primaryColor = "#5CAB7D"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color for sidebar and other secondary elements
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text
textColor = "#333333"

# Font family for all text in the app, except code blocks. 
# Supported values are "sans serif", "serif", and "monospace".
font = "sans serif"
